config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'transactions/create'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :billers, only: [:show, :destroy] do
    resources :transactions, only: [:new, :create]
  end
  get 'my_transactions', to: 'transactions#index', as: :my_transactions
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :downloads, only: [:index, :create, :show]
  post 'language/update'
  resources :bills do
    collection do
      post 'generate'
    end
    member do
      post 'pay'
    end
  end
  resources :repayments, only: [:index, :show]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @billers = Rails.cache.fetch("all_billers", expires_in: 1.hour) do
      Biller.all.to_a
    end
  end
end

app/views/home/index.html.erb
<div class="container text-center mt-5">
  <h1><%= t('custom.call_to_action') %></h1>
  <div class="row justify-content-center mt-5">
    <% @billers.each do |biller| %>
      <div class="col-md-3 mb-4">
        <%= link_to biller_path(biller), class: "text-decoration-none" do %>
          <div class="card bg-white text-dark">
            <div class="card-body">
              <h5 class="card-title"><%= biller.name %></h5>
            </div>
          </div>
        <% end %>
        <% if user_signed_in? && current_user.admin? %> <!-- Conditionally show delete button for admins -->
          <%= button_to 'Delete', biller_path(biller), method: :delete, 
              data: { confirm: 'Are you sure you want to delete this biller?' },
              class: 'btn btn-danger btn-sm mt-2' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>