config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'transactions/create'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :billers, only: [:show, :destroy] do
    resources :transactions, only: [:new, :create]
  end
  get 'my_transactions', to: 'transactions#index', as: :my_transactions
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :downloads, only: [:index, :create, :show]
  post 'language/update'
  resources :bills do
    collection do
      post 'generate'
    end
    member do
      post 'pay'
    end
  end
  resources :repayments, only: [:index, :show]

end

app/models/repayment.rb
class Repayment < ApplicationRecord
  belongs_to :bill
  belongs_to :user

  validates :payment_date, presence: true
  validates :payment_method, presence: true
  validates :bill, presence: true
  validates :user, presence: true
  validates :bill_id, uniqueness: true

  after_create :mark_bill_as_paid

  private

  def mark_bill_as_paid
    bill.pay!
  end
end

app/controllers/repayments_controller.rb
class RepaymentsController < ApplicationController
  def index
    @repayments = current_user.repayments.includes(:bill).order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @repayment = current_user.repayments.find(params[:id])
  end
end

app/views/repayments/index.html.erb
<div class="container mt-4">
  <h1>My Repayments</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Amount</th>
        <th>Payment Method</th>
        <th>Bill</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @repayments.each do |repayment| %>
        <tr>
          <td><%= repayment.created_at.strftime('%B %d, %Y') %></td>
          <td><%= number_to_currency(repayment.bill.bill_amount) %></td>
          <td><%= repayment.payment_method.capitalize %></td>
          <td><%= link_to "Bill ##{repayment.bill.id}", bill_path(repayment.bill) %></td>
          <td>
            <%= link_to 'View', repayment_path(repayment), class: 'btn btn-sm btn-info' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex justify-content-center">
    <%= paginate @repayments %>
  </div>
</div>

app/views/repayments/show.html.erb
<div class="container mt-4">
  <h1>Repayment Details</h1>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Repayment for Bill #<%= @repayment.bill.id %></h5>
      <p class="card-text"><strong>Date:</strong> <%= @repayment.created_at.strftime('%B %d, %Y') %></p>
      <p class="card-text"><strong>Repayment Amount:</strong> <%= number_to_currency(@repayment.bill.bill_amount) %></p>
      <p class="card-text"><strong>Bill Amount:</strong> <%= number_to_currency(@repayment.bill.bill_amount) %></p>
      <p class="card-text"><strong>Payment Method:</strong> <%= @repayment.payment_method.capitalize %></p>
      <%= link_to 'Back to Repayments', repayments_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>