config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'transactions/create'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :billers, only: [:show, :destroy] do
    resources :transactions, only: [:new, :create]
  end
  get 'my_transactions', to: 'transactions#index', as: :my_transactions
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :downloads, only: [:index, :create, :show]
  post 'language/update'
  resources :bills do
    collection do
      post 'generate'
    end
    member do
      post 'pay'
    end
  end
  resources :repayments, only: [:index, :show]

end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #dc3545;">
  <div class="container-fluid">
    <button class="navbar-toggler order-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <a class="navbar-brand mx-auto order-1 order-lg-0 flex-grow-1 text-center" href="/">
      <h1 class="mb-0">Easypay</h1>
    </a>
    
    <div class="collapse navbar-collapse order-2" id="navbarNav">
      <ul class="navbar-nav ms-auto align-items-center">
          <% if user_signed_in? %>
            <% if user_signed_in? && current_user.admin? %>
             <li class="nav-item me-4 align-items-center d-flex">
             <%= link_to "Admin Dashboard", admin_dashboard_path, class: "nav-link" %>
             </li>
            <% end %>
          <li class="nav-item me-4">
           <% if current_user&.admin? %>
            <%= link_to 'Sidekiq Dashboard', sidekiq_web_path, class:"nav-link"%>
           <% end %>
           </li>
           <li class="nav-item me-4">
        <span class="navbar-text">
          <%= t('buttons.avl_credits') %>: <span class="fs-5 fw-bold">₹<%= number_with_precision(current_user.credit, precision: 2) %></span>
        </span>
      </li>
          <li class="nav-item me-4">
            <%= link_to "My Bills", bills_path, class: "nav-link" %>
          </li>
          <li class="nav-item me-4">
            <%= link_to "My Repayments", repayments_path, class: "nav-link" %>
          </li>

          <li class="nav-item me-4">
            <%= link_to t('buttons.my_txns'), my_transactions_path, class: "nav-link" %>
          </li>
          <li class="nav-item me-4">
          <%= link_to t('buttons.my_downd'), downloads_path, class: "nav-link" %>
          </li>
          <li class="nav-item" me-4>
            <%= link_to t('buttons.edit_prof'), edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item" me-4>
            <%= link_to t('buttons.sign_out'), destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('buttons.sign_up'), new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t('buttons.sign_in'), new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<html>
  <head>
    <title>Easypay</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
      body {
        background-color: white;
        color: black;
        font-family: 'Helvetica Neue', sans-serif;
      }
      .btn-custom {
        background-color: #FF5B45;
        color: white;
        border: none;
        font-size: 18px;
        padding: 10px 20px;
      }
      .btn-custom:hover {
        background-color: #FF3D22;
        color: white;
      }
      .card {
        transition: transform 0.3s;
      }
      .card:hover {
        transform: scale(1.05);
      }
      .btn-danger {
        background-color: #FF5B45;
        border-color: #FF5B45;
      }
      .btn-danger:hover {
        background-color: #FF3D22;
        border-color: #FF3D22;
      }
      .btn-outline-light:hover {
        color: #FF5B45;
      }
    </style>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
     <%= render 'shared/language_switcher' %>

    <div class="container mt-4">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>